server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081 # Đi thẳng đến user-service
          predicates:
            - Path=/api/auth/**, /api/users/** # Xóa /v1/
          # Không cần StripPrefix, vì đường dẫn đã khớp với Controller

        - id: recipe-service
          uri: http://localhost:8082 # Đi thẳng đến recipe-service
          predicates:
            - Path=/api/recipes/** # Xóa /v1/
          # Không cần StripPrefix

        - id: ai-service
          # Port 8000 được định nghĩa trong recipe-service properties
          uri: http://localhost:8000
          predicates:
            - Path=/api/ai/**
          # Giữ nguyên /api/ai/ vì app.py cũng dùng /api/ai/
          filters:
            - RewritePath=/api/ai/(?<segment>.*), /api/ai/$\{segment}

# Tắt Eureka client ở Gateway nếu không dùng
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

application:
  security:
    jwt:
      # NÊN DÙNG BIẾN MÔI TRƯỜNG
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000