server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081 # Địa chỉ của user-service
          predicates:
            - Path=/api/auth/**, /api/users/**

        - id: recipe-service
          uri: http://localhost:8082 # Địa chỉ của recipe-service
          predicates:
            - Path=/api/recipes/**

# Thêm cấu hình JWT giống hệt các service khác
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000