server:
  port: 8080

spring:
  application:
    name: api-gateway
  # (Các phần khác)
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**
          # Thêm bộ lọc cho user-service để đảm bảo tính nhất quán
          filters:
            - StripPrefix=2
        - id: recipe-service
          uri: lb://recipe-service
          predicates:
            - Path=/api/v1/recipes/**
          # === THÊM BỘ LỌC NÀY VÀO ===
          filters:
            - StripPrefix=2

        # --- THÊM ROUTE MỚI NÀY VÀO ---
        - id: ai-service
          uri: http://localhost:8083 # Địa chỉ của ai-service
          predicates:
            - Path=/api/ai/**

# Thêm cấu hình JWT giống hệt các service khác
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

