server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route 1: User Service
        - id: user-service
          uri: http://user-service:8081  # ĐÃ SỬA: Dùng tên service trong Docker network
          predicates:
            - Path=/api/auth/**, /api/users/**
          filters:
            - name: Authentication  # Áp dụng filter xác thực JWT

        # Route 2: Recipe Service
        - id: recipe-service
          uri: http://recipe-service:8082  # ĐÃ SỬA: Dùng tên service trong Docker network
          predicates:
            - Path=/api/recipes/**
          filters:
            - name: Authentication

        # Route 3: AI Service
        - id: ai-service
          uri: http://ai-service:8000  # ĐÃ SỬA: Dùng tên service trong Docker network
          predicates:
            - Path=/api/ai/**
          filters:
            - name: Authentication

# Tắt Eureka (không dùng service discovery)
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

# JWT Configuration
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000